// Package conformance provides a shared test suite that exercises the
// storage.Backend contract against any implementation. Both the SQLite and
// pgvector backends run this suite to ensure behavioural parity.
//
// Usage from a backend's _test.go file:
//
//	func TestConformance(t *testing.T) {
//	    backend := newBackend(t) // construct a fresh backend
//	    defer backend.Close()
//	    conformance.RunSuite(t, backend, dims)
//	}
package conformance

import (
	"context"
	"math"
	"testing"

	"github.com/petal-labs/cortex/internal/storage"
)

// RunSuite runs the full dual-backend conformance suite against b. Each domain
// uses a unique namespace so sub-tests do not interfere with each other on the
// shared backend instance.
//
// dims is the embedding dimension the backend was configured with; all
// embeddings generated by the suite use this dimension.
func RunSuite(t *testing.T, b storage.Backend, dims int) {
	ctx := context.Background()

	t.Run("Lifecycle", func(t *testing.T) {
		testLifecycle(ctx, t, b)
	})

	t.Run("Conversation", func(t *testing.T) {
		testConversation(ctx, t, b, dims)
	})

	t.Run("Knowledge", func(t *testing.T) {
		testKnowledge(ctx, t, b, dims)
	})

	t.Run("Context", func(t *testing.T) {
		testContext(ctx, t, b)
	})

	t.Run("Entity", func(t *testing.T) {
		testEntity(ctx, t, b, dims)
	})

	t.Run("GarbageCollection", func(t *testing.T) {
		testGarbageCollection(ctx, t, b, dims)
	})
}

// normalizeVector returns a unit-normalized copy of v.
func normalizeVector(v []float32) []float32 {
	var sum float32
	for _, val := range v {
		sum += val * val
	}
	norm := float32(math.Sqrt(float64(sum)))
	result := make([]float32, len(v))
	if norm == 0 {
		return result
	}
	for i, val := range v {
		result[i] = val / norm
	}
	return result
}

// createTestEmbedding builds a deterministic, normalized embedding of the
// requested dimension. Vectors with nearby seeds are more similar than those
// with distant seeds, enabling search ordering assertions.
func createTestEmbedding(seed float32, dims int) []float32 {
	embedding := make([]float32, dims)
	for i := 0; i < dims; i++ {
		embedding[i] = seed + float32(i)*0.01
	}
	return normalizeVector(embedding)
}
